#! /bin/env bash

menu_pos="-x C -y C"

main() {
    case "$1" in
        "")
            tmux display-menu -T " MENU " $menu_pos \
                "󰄨  Resource monitor    " r 'neww -n Resources btop' \
                "  Journal"              j 'neww -n Journal "journal $JOURNAL_ENC_DIR"' \
                "󱉟  Help"                 h 'neww -n Help help' \
                "" \
                "  Main session"         m "new-session -A -s main -c $HOME" \
                "󱁴  Find window"          f "display-popup -w 48 -h 24 -T ' Find window ' -E tps-win" \
                "󰉗  New project"          n "display-popup -w 50% -h 50% -T ' New Project ' -EE tps-new" \
                "" \
                "  Packages…"            p 'run "globalmenu packages"' \
                "  Services…"            s 'run "globalmenu services"' \
                "󱧼  Configs…"             c 'run "globalmenu configs"' \
                "󱁤  Utilities…"           u 'run "globalmenu utils"' \
                "" \
                "  Reboot"               R 'display-popup -w 30% -h 8 -E "gum confirm --default=no \"Reboot now?\" && reboot"' \
                "󰐥  Shutdown"             S 'display-popup -w 30% -h 8 -E "gum confirm --default=no \"Shutdown now?\" && shutdown -h now"' \
        ;;

        "packages")
            tmux display-menu -T " MENU > PACKAGES " $menu_pos \
                "󰇚  Install             " i 'display-popup -w 80% -h 80% -T " Install a new package " -EE packages add' \
                "󰛌  Remove"               r 'display-popup -w 80% -h 80% -T " Remove a package " -EE packages remove' \
                "" \
                "  List"                 l 'display-popup -w 80% -h 80% -T " Installed packages " -E packages installed' \
                "  List AUR"             L 'display-popup -w 80% -h 80% -T " Installed packages " -E packages installed-aur' \
                "󰦗  Check updates"        c 'display-popup -w 80% -h 80% -T " Available Updates " -E "checkupdates | less"' \
                "󰚰  Update all"           u 'neww -n "Full system update" packages upgrade' \
                "󰈞  File owner"           f 'display-popup -w 80% -h 80% -T " Which package owns a file " -E packages owner' \
                "" \
                "  Arch News"            n 'run "xdg-open https://archlinux.org/news"' \
                "  Arch Wiki"            w 'run "xdg-open https://wiki.archlinux.org"' \
                "  AUR (if it's up)"     a 'run "xdg-open https://aur.archlinux.org"' \
                "" \
                "󰜱  Back"                 q 'run globalmenu'
        ;;

        "configs")
            tmux display-menu -T " MENU > CONFIGS " $menu_pos \
                "󱁻  Dotfiles            " d "run 'tps $DOTFILES_PATH'" \
                "" \
                "󰊠  Ghostty"              g "run 'tps $DOTFILES_PATH config/ghostty/config'" \
                "  Neovim"               n "run 'tps $DEV_PATH/personal/config.nvim'" \
                "  Hyprland"             h "run 'tps $DOTFILES_PATH config/hypr/hyprland.conf'" \
                "󰠷  Waybar"               w "run 'tps $DOTFILES_PATH config/waybar/config'" \
                "  Globalmenu"           m "run 'tps $DOTFILES_PATH local-bin/globalmenu'" \
                "" \
                "󰏗  Pacman"               P 'neww -n "Pacman config" sudoedit /etc/pacman.conf' \
                "󰈙  Hosts"                H 'neww -n "Hosts file" sudoedit /etc/hosts' \
                "" \
                "󰜱  Back"                 q 'run "globalmenu"'
        ;;

        "services")
            tmux display-menu -T " MENU > SERVICES " $menu_pos \
                "󰐊  Start               " s 'display-popup -w 80% -h 80% -T " Start service " -EE "services start"' \
                "󰓛  Stop"                 k 'display-popup -w 80% -h 80% -T " Start service " -EE "services stop"' \
                "  Restart"              r 'display-popup -w 80% -h 80% -T " Restart service " -EE "services restart"' \
                "  Enable"               e 'display-popup -w 80% -h 80% -T " Enable service " -EE "services enable"' \
                "  Disable"              d 'display-popup -w 80% -h 80% -T " Disable service " -EE "services disable"' \
                "" \
                "  List all"             l 'display-popup -w 80% -h 80% -T " Services " -E "services list"' \
                "  Active"               a 'display-popup -w 80% -h 80% -T " Services (active) " -E "services list active"' \
                "  Inactive"             i 'display-popup -w 80% -h 80% -T " Services (inactive) " -E "services list inactive"' \
                "  Failed"               f 'display-popup -w 80% -h 80% -T " Services (failed) " -E "services list failed"' \
                "" \
                "󰝒  Create new"           C 'neww -n "New service" "services new"' \
                "󱇧  Edit"                 E 'neww -n "Edit service" "services edit"' \
                "󰮘  Delete"               D 'display-popup -w 50% -h 20 -T " Delete service " -EE "services delete"' \
                "󰑐  Reload daemon"        R 'display-popup -w 50% -h 6 -T " Reload daemon " -EE "systemctl daemon-reload"' \
                "" \
                "󰜱  Back"                 q 'run "globalmenu"'
        ;;

        "utils")
            tmux display-menu -T " MENU > UTILITIES " $menu_pos \
                "󱝁  Setup"                s "display-popup -w 80% -h 80% -T ' Setup ' setup " \
                "󱩖  Reset RGB           " r "display-popup -w 50% -h 12 -T ' Reset RGB ' -EE 'openrgb -p ~/.config/OpenRGB/viridescent.orp'" \
                "󱅞  Reset faillock"       f "display-popup -w 50% -h 10 -T ' Reset faillock ' -EE 'faillock --user $USER --reset' " \
                "󱂇  Ping google.com"      p "display-popup -w 80% -h 80% -T ' Pinging google.com ' -EE 'gping google.com' " \
                "" \
                "󰜱  Back"                 q 'run "globalmenu"'
        ;;
    esac
}

journal_status_icon() {
    if journal status &>/dev/null; then
        echo "#[fg=${VIRID_YELLOW}] "
    else
        echo "#[fg=${VIRID_GREEN}] "
    fi
}

journal_status_text() {
    if journal status &>/dev/null; then
        echo "#[fg=${VIRID_YELLOW}]Unlocked"
    else
        echo "#[fg=${VIRID_GREEN}]Locked"
    fi
}

main $@
