#! /usr/bin/env bash

FZF_OPTS="--preview-window down --bind ctrl-u:preview-up,ctrl-d:preview-down"

arg="${1,,}"

case "$arg" in
    "")
        echo -e "Add\nRemove\nInstalled\nUpgrade" | fzf $FZF_OPTS | xargs -ro packages
    ;;
    "add")
        paru -Slq | fzf $FZF_OPTS --multi --preview 'paru -Si {1}' | xargs -ro paru -Sy
    ;;
    "remove")
        pacman -Qq | fzf $FZF_OPTS --multi --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns
    ;;
    "installed")
        pacman -Qq | fzf $FZF_OPTS --multi --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'
    ;;
    "installed-aur")
        pacman -Qqm | fzf $FZF_OPTS --multi --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'
    ;;
    "owner")
        file=$(fzfr '/' $FZF_OPTS)
        if [ ! -z "$file" ]; then
            pacman -Qi $(pacman -Qqo "$file") | less
        fi
    ;;
    "upgrade")
        gum confirm "Perform a full system update?" --default=no && paru -Syu
    ;;
    *)
        echo "wtf is \"$arg\"?"
    ;;
esac
