#! /usr/bin/env bash

if [ -z $SCRIPTS_PATH ]; then
    SCRIPTS_PATH="$DOTFILES_PATH/scripts/setup"
fi

help() {
    arg="$1"
    name=$(basename "$0")
    fullpath=$(realpath "$0")

    if [ ! -z "$arg" ]; then
        script="$SCRIPTS_PATH/$arg"

        if [ ! -f "$script" ]; then
            echo "setup script '$arg' does not exist"
            exit 1
        fi

        if pacman -Qi bat &> /dev/null; then
            bat "$script"
        else
            cat "$script" | less
        fi

        exit 0
    fi

    echo "$(basename "$0") <SCRIPT>"
    echo
    echo "SCRIPTS:"

    echo
    find "$SCRIPTS_PATH" -type f -exec basename {} ';' | sort | sed 's/^/    /'
    echo

    echo "To see exactly what packages are installed by each set, run the below command to read the source code. You can read bash, right?"
    echo
    echo "    help <SCRIPT>"
    echo

    echo "Lastly, this script is not intended to be run unattended."
    echo "I know myself. HEY ME! Sit down and don't get distracted. Watch for errors and be ready to kill that sumbish."
}

if [ "$1" == "" ]; then
    choice=$(fd . $DOTFILES_PATH/scripts/setup --type=f --format={/} | fzf)
    if [ -z "$choice" ]; then
        exit 0
    fi
    $0 "$choice"
    exit $?
fi

if [ "$1" == "help" ]; then
    help "$2"
    exit 1
fi

if [ ! -f "$SCRIPTS_PATH/$1" ]; then
    echo "setup script '$1' does not exist"
    exit 1
fi

source "$SCRIPTS_PATH/$1"  
exit $?
