#! /bin/env bash
# My version of tps, adapted from ThePrimegen's script:
# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer"

path=$1

if [ -z "$path" ]; then
    choice="$(fd . "$DEV_PATH" -H -t dir -L --exact-depth 2 | sed "s|^$DEV_PATH/||" | fzf)"
    [[ -z "$choice" ]] && exit 0
    path="$DEV_PATH/$choice"
elif [[ "$path" == "here" ]]; then
    path="$PWD"
fi

[[ -z "$path" ]] && exit 0

session_name=$(basename "$path" | tr . _)

if [[ -z "$TMUX" ]]; then
    tmux new-session -A -s "$session_name" -c "$path"
fi

if ! tmux has-session -t=$session_name 2> /dev/null; then
    tmux new-session -ds "$session_name" -c "$path"

    if [ -f "$path/.project" ]; then
        (cd "$path" && source "$path/.project")
    fi
fi

tmux switch-client -t $session_name
