#! /usr/bin/env bash
# Fuzzy find and edit a file in Neovim from any window in the project's session.

file="$1"

if [ -z "$file" ]; then
    file=$(fzf --prompt 'File: ' --style full --preview 'bat --color=always --style=plain {}')
fi

if [ -z "$file" ]; then
    exit
fi

if tmux select-window -t nvim 2> /dev/null; then
    tmux send-keys -t nvim Escape ":e $file" Enter
else
    tmux neww -bt 1 nvim "$file"
fi
