#! /usr/bin/env bash
# Fuzzy find and edit a file in Neovim from any window in the project's session.

file="$1"

if [ -z "$file" ]; then
    file=$(rg -L --files --hidden --glob "!**/.git/**" | fzf --preview-window down --preview 'bat --color=always --style=plain {}' --bind ctrl-u:preview-up,ctrl-d:preview-down)
fi

if [ -z "$file" ]; then
    exit
fi

session=$(tmux display-message -p '#S')
editor_win="$session:nvim"

if tmux select-window -t "$editor_win" 2> /dev/null; then
    tmux send-keys -t nvim Escape ":e $file" Enter
else
    tmux neww -bt 1 nvim "$file"
fi
