#! /usr/bin/env bash

heading "FONTS"
sudo pacman -S --needed noto-fonts ttf-roboto ttf-jetbrains-mono ttf-jetbrains-mono-nerd
paru -S --needed ttf-ms-win10-auto ttf-ms-win11-auto

if [ ! -d "$HOME/.config/oh-my-zsh/" ]; then
    heading "OH MY ZSH"
    export ZSH="$HOME/.config/oh-my-zsh"
    mkdir -p $ZSH/custom/plugins
    git clone https://github.com/zsh-users/zsh-completions $ZSH/custom/plugins/zsh-completions
    git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH/custom/plugins/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-history-substring-search $ZSH/custom/plugins/zsh-history-substring-search
    git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git $ZSH/custom/plugins/fast-syntax-highlighting
    (cd $dir; stow -t $ZSH config/oh-my-zsh)
fi

sh -c "$(curl -sfSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
heading "TMUX"
sudo pacman -S --needed tmux
git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm

heading "NEOVIM"
if [ ! -d ~/.config/nvim ]; then
    git clone git@github.com:mecha/config.nvim ~/.config/nvim
fi
sudo pacman -S --needed neovim

heading "PROGRAMMING LANGUAGES"
sudo pacman -S --needed go delve nodejs-lts-iron npm yarn nvm php php-sqlite composer
sudo sed -i 's/^;extension=sqlite3$/extension=sqlite3/g' /etc/php/php.ini
sudo sed -i 's/^;extension=iconv$/extension=iconv/g' /etc/php/php.ini
sudo sed -i 's/^;extension=zip$/extension=zip/g' /etc/php/php.ini

heading "DOCKER"
sudo pacman -S --needed docker docker-compose
sudo usermod -aG docker $USER
newgrp docker

heading "GIT"
sudo pacman -S --needed lazygit
