#! /usr/bin/env bash

heading "===> DRIVERS"
sudo pacman -S --needed vulkan-radeon lib32-vulkan-radeon

heading "===> OPTIMISATIONS & MONITORING"
sudo pacman -S --needed gamemode mangohud

heading "===> LAUNCHERS"
sudo pacman -S --needed steam lutris

heading "===> MINECRAFT"
sudo pacman -S --needed prismlauncher jre8-openjdk-headless jre8-openjdk jre17-openjdk jre21-openjdk

heading "DISCORD"
flatpak install flathub com.discordapp.Discord
